### ISSUE TITLE
Warning falha ao copiar

### ISSUE THREAD

**Issue by tiagovtg** [joomlapro/pt-BR_joomla_lang_full#1]
Atenção
Falha ao copiar

JInstaller: :Install: Falha ao copiar o arquivo \pt-BR_joomla_lang_full-master\TinyMCE_pt-BR\tinymce\langs\pt-BR.js para \media\editors\tinymce\langs\pt-BR.js

**Comment by brunowego** [comment]
Olá Tiago, fiz alguns testes e não obtive o mesmo erro. Não seria um problema de permissão de pastas e arquivos?

**Comment by tiagovtg** [comment]
nao sei dizer, mas pra tentar ajudar, o ambiente aqui é win7.

creio que se tenha as permissões normais.

Em 7 de outubro de 2013 14:15, Bruno Batista notifications@github.comescreveu:

> Olá Tiago, fiz alguns testes e não obtive o mesmo erro. Não seria um
> problema de permissão de pastas e arquivos?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joomlapro/pt-BR_joomla_lang_full/issues/1#issuecomment-25827050
> .

## 

Tiago

61 8120 3003 Tim
61 8412 9685 Claro

**Comment by brunowego** [comment]
Fechando.
